/**
 * Group 1: Core System Architecture Articles
 * Comprehensive, production-grade HLD breakdowns.
 */

module.exports = {
  chatgpt: {
    title: "Design ChatGPT (LLM Streaming Inference Platform)",
    slug: "chatgpt",
    description: "Architect a large-scale conversational AI inference platform capable of serving 200M+ users with low-latency token streaming, KV cache optimization, and GPU scheduling.",
    difficulty: "HARD",
    category: "System Architectures",
    estimatedTimeMinutes: 45,
    tags: ["System Architectures", "AI / LLM", "Streaming", "Real-Time", "GPU Infrastructure", "Distributed Systems"],
    isPremium: true,
    contentMarkdown: `# Design ChatGPT (LLM Streaming Inference Platform)

ChatGPT is a real-time conversational AI system serving hundreds of millions of users worldwide. Unlike traditional web services that compute a database query and return a static JSON payload, conversational AI platforms run multi-billion-parameter neural network weights across distributed GPU clusters, streaming generated tokens sequentially to clients with strict latency budgets.

---

## 1. System Requirements

### Functional Requirements
1. **Interactive Chat Prompts**: Users can submit text prompts to ongoing or new chat conversations and receive AI-generated completions.
2. **Real-time Token Streaming**: The response must stream token-by-token back to the user as generated by the inference engine (Server-Sent Events / WebSockets).
3. **Multi-Turn Context**: Previous conversational turns within the session must be retained and incorporated into subsequent prompts up to the model's context limit.
4. **Chat History Management**: Users can list past conversations, retrieve full chat transcripts, rename threads, and delete history.
5. **Generation Cancellation**: Users can interrupt generation mid-stream, immediately halting GPU compute for that request.

### Non-Functional Requirements
1. **Time-To-First-Token (TTFT)**: Under 250ms for prompt processing and initial token emission.
2. **Generation Latency (Inter-Token Latency)**: 30–50ms per token (20–30 tokens/second), matching or exceeding human reading speed.
3. **Availability & Fault Tolerance**: 99.99% uptime for the chat gateway; worker node crashes should not drop user connections.
4. **Scalability**: Support 200 Million Daily Active Users (DAU), 20,000 peak prompt QPS, and up to 150,000 concurrent streaming responses.
5. **Cost & GPU Efficiency**: Maximize GPU tensor core utilization via continuous batching, KV caching, and prompt caching.

---

## 2. Scale & Capacity Estimation

### Traffic Calculations
* **Daily Active Users (DAU)**: $200\\text{ Million}$
* **Average Prompts Per User**: 6 prompts/day $\\rightarrow 1.2\\text{ Billion prompts/day}$
* **Average QPS**: $\\frac{1.2 \\times 10^9}{86,400} \\approx 14,000\\text{ QPS}$
* **Peak QPS (2x multiplier)**: $\\approx 28,000\\text{ QPS}$
* **Average Generation Time**: 10 seconds per response (approx. 250 tokens @ 25 tokens/sec).
* **Concurrent Active Streams**: $28,000\\text{ QPS} \\times 10\\text{s} = 280,000\\text{ concurrent streaming connections}$.

### Storage Estimation
* **Average Prompt Length**: 100 tokens (\\approx 400 bytes).
* **Average Completion Length**: 250 tokens (\\approx 1,000 bytes).
* **Daily Conversation Data**: $1.2 \\times 10^9 \\times 1.5\\text{ KB} \\approx 1.8\\text{ TB/day}$.
* **Annual Storage (with metadata & indexing)**: $\\approx 800\\text{ TB/year}$.

---

## 3. High-Level Architecture Blueprint

\`\`\`
                                  +-----------------------+
                                  |   Client App / Web    |
                                  +-----------+-----------+
                                              |
                                              | HTTPS / WSS / SSE
                                              v
                                  +-----------------------+
                                  |    Cloudflare CDN     |
                                  |   (DDoS & TLS Term)   |
                                  +-----------+-----------+
                                              |
                                              v
                                  +-----------------------+
                                  |      API Gateway      |
                                  | (Auth, Rate Limiting) |
                                  +-----+-----------+-----+
                                        |           |
             +--------------------------+           +--------------------------+
             |                                                                 |
             v                                                                 v
+------------------------+                                         +------------------------+
|   Conversation Service |                                         |   Streaming Gateway    |
| (CRUD, History, Meta)  |                                         | (SSE Connection Hub)   |
+-----------+------------+                                         +-----------+------------+
            |                                                                  ^
            v                                                                  | Token Stream
+------------------------+         +-----------------------+                   |
|   PostgreSQL / Scylla  |         |     Kafka Message     |                   |
|  (Chat Messages DB)    |         |   Prompt Queue Pool   |                   |
+------------------------+         +-----------+-----------+                   |
                                               |                               |
                                               v                               |
                                   +-----------------------+                   |
                                   |    Inference Router   |                   |
                                   |   & KV Cache Arbiter  |                   |
                                   +-----------+-----------+                   |
                                               |                               |
                                               v Dispatch                      |
                                   +-----------------------+                   |
                                   |    GPU Worker Node    |                   |
                                   | (vLLM / PagedAttention|-------------------+
                                   | TensorRT-LLM Engine)  |
                                   +-----------------------+
\`\`\`

---

## 4. Detailed Component Workflows

### A. The Generation Request Lifecycle
1. **Request Ingestion**: User sends \`POST /api/v1/conversations/{id}/messages\` with the prompt text.
2. **Context Assembly**: The \`Conversation Service\` fetches the last $N$ turns from the conversation store. If the context exceeds token thresholds, historical turns are dynamically summarized.
3. **Moderation & Safety Check**: An asynchronous lightweight classifier filters out toxic prompts before invoking expensive GPU workloads.
4. **Queue & Scheduling**: The prompt, along with user priority tier (Free vs Plus/Pro), is enqueued into a distributed Kafka partition.
5. **Inference Router Dispatch**: The router checks which GPU worker node already has the KV cache loaded for that \`conversation_id\` (Prefix/Prompt Cache Affinity).
6. **Continuous Batching Execution**: The GPU worker adds the prompt to its running iteration batch. In each decoding step (forward pass):
   * New tokens are sampled from logits.
   * Emitted tokens are published to a Redis pub/sub channel or gRPC stream.
   * The \`Streaming Gateway\` writes the token to the client's active Server-Sent Event (SSE) connection.
7. **Stream Finalization**: An \`[DONE]\` sentinel token signals the end of generation. The complete completion is written back to the primary database.

---

## 5. Staff-Level Deep Dives

### Deep Dive 1: KV Caching & PagedAttention
During transformer auto-regressive generation, computing attention requires the Key ($K$) and Value ($V$) matrices of all previous tokens in the sequence. Without caching, generation has $O(N^2)$ complexity.
* **The Problem**: Storing KV vectors in GPU HBM (High Bandwidth Memory) consumes huge capacity (e.g. 1-2 GB per long sequence). Traditional contiguous memory allocation causes up to 60-80% memory fragmentation.
* **The Solution (PagedAttention)**: Inspired by OS virtual memory paging, PagedAttention partitions KV tensors into fixed-size blocks (e.g., 16 tokens per block).
* Blocks are stored in non-contiguous physical GPU memory spaces mapped by a page table.
* Enables dynamic memory allocation, allowing concurrent batch size on an 8x H100 node to increase by $2.5\\times - 4\\times$.

### Deep Dive 2: Continuous Batching (Iteration-Level Scheduling)
* **Static Batching Flaw**: Traditional deep learning batches requests together. If Request A generates 20 tokens and Request B generates 500 tokens, the GPU sits idle waiting for Request B while Request A's slot is wasted.
* **Continuous Batching**: Operates at the iteration level rather than request level. Once Request A finishes its 20th token, it is immediately evicted from the batch, and a new prompt Request C is inserted into the batch for the next iteration without restarting the GPU pipeline.

### Deep Dive 3: Client Connection Management & Resilient Streaming
* **Server-Sent Events (SSE) vs WebSockets**: SSE uses standard HTTP/2 multiplexing, automatic reconnects, and lightweight unidirectional streaming, eliminating the overhead of full-duplex WebSocket state tables.
* **Disconnect Recovery**: Every token chunk carries an incremental sequence number (\`seq_id\`). If a mobile client loses connection on cell towers, it reconnects using:
  \`GET /api/v1/conversations/{id}/stream?last_seq_id=42\`
* The \`Streaming Gateway\` replays buffered tokens from an in-memory Redis ring buffer (TTL: 60s) before resuming live generation.

### Deep Dive 4: Generation Cancellation & GPU Resource Reclaiming
* When a user clicks **"Stop Generating"**, the client sends \`POST /api/v1/conversations/{id}/cancel\`.
* The API Gateway emits a cancellation signal carrying the \`request_id\` across the internal message bus.
* The GPU inference worker checks a local atomic cancellation flag before executing the next decoding step. If flagged, it evicts the sequence's KV page tables immediately, freeing memory back to the GPU pool in less than 50ms.

---

## 6. Database Schema & Data Models

### Conversations Table (\`conversations\`)
\`\`\`sql
CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    model_version VARCHAR(64) NOT NULL DEFAULT 'gpt-4o',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_archived BOOLEAN DEFAULT FALSE
);
CREATE INDEX idx_conversations_user ON conversations(user_id, updated_at DESC);
\`\`\`

### Messages Table (\`messages\`)
\`\`\`sql
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_role VARCHAR(16) NOT NULL CHECK (sender_role IN ('system', 'user', 'assistant')),
    content TEXT NOT NULL,
    token_count INT NOT NULL,
    finish_reason VARCHAR(32) DEFAULT 'stop',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX idx_messages_conversation ON messages(conversation_id, created_at ASC);
\`\`\`

---

## 7. Trade-offs & Architecture Decisions

| Decision Factor | Choice A: WebSockets | Choice B: Server-Sent Events (SSE) (Selected) | Rationale |
| :--- | :--- | :--- | :--- |
| **Protocol Simplicity** | Full-duplex bidirectional | Unidirectional over HTTP/2 | Chat generation is inherently unidirectional from server to client. HTTP/2 provides built-in compression and multiplexing. |
| **GPU Scheduling** | FCFS (First Come First Serve) | Priority Continuous Batching | Paid subscribers (Plus/Team) bypass queue delays with guaranteed GPU slice allocations. |
| **KV Cache Strategy** | Per-instance local memory | Prefix-Aware Affinity Router | Prompts sharing common system instructions or conversation context are routed to the same worker to reuse warm KV cache blocks. |
`
  },

  "google-docs": {
    title: "Design Google Docs (Collaborative Real-time Document Editing)",
    slug: "google-docs",
    description: "Design a collaborative rich-text editor supporting concurrent real-time edits, character-level synchronization, conflict resolution via CRDTs / OT, and revision history.",
    difficulty: "HARD",
    category: "System Architectures",
    estimatedTimeMinutes: 45,
    tags: ["System Architectures", "Real-Time", "CRDT", "Operational Transformation", "WebSockets", "Distributed Consensus"],
    isPremium: true,
    contentMarkdown: `# Design Google Docs (Collaborative Real-time Editor)

Google Docs enables multiple users across different continents to simultaneously edit the same document in real time, view collaborators' cursor positions, and resolve concurrent typing collisions without data loss or UI freezing.

---

## 1. System Requirements

### Functional Requirements
1. **Real-time Concurrent Editing**: Multiple users can edit the same document simultaneously, seeing each other's changes in under 100ms.
2. **Conflict Resolution & Convergence**: If two users type at the exact same cursor position simultaneously, the final document state must converge identically for all participants.
3. **Presence & Caret Tracking**: Display collaborators' live cursor coordinates and selection highlights.
4. **Version History & Restore**: View point-in-time snapshots and roll back to previous revisions.
5. **Offline Editing & Re-sync**: Allow users to edit offline and merge modifications when internet connectivity returns.

### Non-Functional Requirements
1. **Low Sync Latency**: End-to-end operation dissemination latency $< 100\\text{ms}$ globally.
2. **Consistency Guarantee**: Eventual consistency with strict convergence guarantees (no lost keystrokes).
3. **Availability & Scalability**: 99.99% availability; support up to 100 concurrent active typers on a single document.
4. **Durability**: Zero data loss upon browser refresh, crash, or server failure.

---

## 2. Capacity & Scale Estimation

* **Daily Active Users (DAU)**: $100\\text{ Million}$
* **Concurrently Open Documents**: $5\\text{ Million}$
* **Average Keystrokes / Edits per Active Document**: 5 operations per second.
* **System Peak Ingress Operations**: $5\\text{ Million} \\times 5 = 25\\text{ Million ops/sec}$.
* **Average Operation Payload**: 64 bytes (character, index/ID, timestamp, user_id).
* **Network Throughput**: $25 \\times 10^6 \\times 64\\text{ bytes} \\approx 1.6\\text{ GB/sec}$.

---

## 3. Architecture Blueprint

\`\`\`
                                  +-----------------------+
                                  |   Collaborator A/B    |
                                  +-----------+-----------+
                                              |
                                              | WebSockets (WSS)
                                              v
                                  +-----------------------+
                                  |     Load Balancer     |
                                  | (Session Sticky Hash) |
                                  +-----------+-----------+
                                              |
                                              v
                                  +-----------------------+
                                  | Document Room Server  |
                                  |   (In-Memory Actor    |
                                  |  Engine & OT/CRDT Hub)|
                                  +-----+-----------+-----+
                                        |           |
             +--------------------------+           +--------------------------+
             |                                                                 |
             v Broadcast (Redis Pub/Sub)                                       v Async Snapshot (10s)
+------------------------+                                         +------------------------+
| Other Room Servers     |                                         | Document Storage Svc   |
| (Multi-region replicas)|                                         | (PostgreSQL + S3 Docs) |
+------------------------+                                         +------------------------+
\`\`\`

---

## 4. Conflict Resolution: OT vs. CRDT

### Operational Transformation (OT)
Used historically by Google Docs.
* **Concept**: When an operation arrives that was executed against an older document version, the server transforms the operation's position offset against concurrent operations.
* **Pros**: Compact payload size (only sends \`Insert('x', at: 14)\`); low memory overhead.
* **Cons**: Requires a centralized single-threaded server per document to establish global operation ordering; computationally complex transformation matrices.

### Conflict-Free Replicated Data Types (CRDTs)
Used by Figma, Apple Notes, and modern collaborative platforms (Yjs, Automerge).
* **Concept**: Every character is assigned a unique, immutable fractional identifier (e.g. between position 1.0 and 2.0, insert 1.5).
* **Pros**: Peer-to-peer friendly, highly decentralized, mathematically guaranteed convergence without a single central sequencer.
* **Cons**: Memory overhead per character (stores metadata IDs and tombstones for deletions).

---

## 5. Staff-Level Deep Dives

### Deep Dive 1: The Centralized Document Room Actor Pattern
To avoid distributed consensus overhead on every keystroke:
1. Each active document is hosted on a specific **Document Room Server** using consistent hashing on \`document_id\`.
2. The server holds the canonical document state in RAM.
3. Inbound user keystrokes are processed sequentially in a single event loop.
4. The server assigns an incrementing monotonic \`revision_number\` (e.g., rev 104) and broadcasts the acknowledged operation to all connected sockets.
5. Clients receive the transformed delta and adjust their local visual trees.

### Deep Dive 2: Snapshotting & Compaction
* Typing thousands of characters generates millions of incremental operations.
* A background worker periodically creates a compressed snapshot of the full document state every 100 revisions or every 10 seconds.
* Older operational logs are archived to cold object storage (S3/GCS), keeping document load times sub-second for new joiners.

### Deep Dive 3: Disconnected & Offline Sync
* While offline, the client logs operations in an IndexedDB append-only queue.
* When reconnected, the client transmits its local change vector.
* Using CRDTs or three-way merge algorithms, local offline edits are interleaved into the server state without overriding remote colleagues' work.
`
  },

  "payment-system": {
    title: "Design an Idempotent Payment System",
    slug: "payment-system",
    description: "Design a mission-critical, double-entry financial ledger and payment processing gateway with strict idempotency, distributed transactions, and reconciliation pipelines.",
    difficulty: "HARD",
    category: "System Architectures",
    estimatedTimeMinutes: 45,
    tags: ["System Architectures", "Fintech", "Idempotency", "Transactions", "Ledger", "Distributed Systems"],
    isPremium: true,
    contentMarkdown: `# Design an Idempotent Payment System (Stripe / PayPal Scale)

Financial payment systems must guarantee that money is never created or destroyed out of thin air, duplicate charges never occur during network timeouts, and every single transaction is immutably audited via double-entry bookkeeping.

---

## 1. System Requirements

### Functional Requirements
1. **Pay-in Processing**: Accept customer payment methods (credit card, bank transfer) and process charge authorizations.
2. **Double-Entry Financial Ledger**: Maintain an immutable accounting record where total debits equal total credits for every transaction.
3. **Third-Party Payment Service Provider (PSP) Integration**: Dispatch external API calls to providers like Visa, Mastercard, or Stripe.
4. **Reconciliation Engine**: Asynchronously compare internal transaction records with daily bank settlement files to catch discrepancies.
5. **Refunds & Chargebacks**: Support full and partial refunds with reversible ledger entries.

### Non-Functional Requirements
1. **Strict Idempotency**: Guarantee exactly-once payment processing even when network retries occur.
2. **Zero Financial Discrepancies**: Total ledger consistency; transactions must satisfy ACID guarantees.
3. **High Availability**: 99.999% uptime for the payment ingestion gateway.
4. **Auditability**: Every modification must be traceable to a cryptographically verifiable transaction log.

---

## 2. Core Concepts: The Double-Entry Ledger

In financial accounting, money does not simply change a single balance column. Instead, every movement of capital is represented as two offsetting entries:
$$\\sum \\text{Debits} = \\sum \\text{Credits}$$

### Example: Customer Buys a $100 Item
\`\`\`
Account                    | Debit   | Credit
---------------------------|---------|---------
Customer Cash Holding      |         | $100.00
Platform Escrow Holding    | $100.00 | 
\`\`\`

Ledger entries are strictly **append-only**. Corrections are made by creating a new reversing entry, never by modifying past database rows.

---

## 3. High-Level Architecture Blueprint

\`\`\`
                               +-----------------------+
                               |     Checkout UI       |
                               +-----------+-----------+
                                           |
                                           | POST /payments (with Idempotency-Key)
                                           v
                               +-----------------------+
                               |    Payment Gateway    |
                               | (Rate Limit & Verify) |
                               +-----------+-----------+
                                           |
                                           v
                               +-----------------------+
                               |    Payment Service    |
                               +-----+-----------+-----+
                                     |           |
          +--------------------------+           +--------------------------+
          |                                                                 |
          v (1. Acquire Lock & Check State)                                 v (2. Insert Pending)
+------------------------+                                         +------------------------+
|   Redis Distributed    |                                         |  PostgreSQL Primary DB |
|   Lock (Redlock)       |                                         | (Orders & Payments)    |
+------------------------+                                         +-----------+------------+
                                                                               |
                                                                               v (3. Enqueue Outbox)
                                                                   +------------------------+
                                                                   |  Transactional Outbox  |
                                                                   |  & Kafka Task Queue    |
                                                                   +-----------+------------+
                                                                               |
                                                                               v
                                                                   +------------------------+
                                                                   | Payment Execution Svc  |
                                                                   +-----------+------------+
                                                                               |
                                                                               v Call External API
                                                                   +------------------------+
                                                                   | Third-Party PSP (Visa) |
                                                                   +------------------------+
\`\`\`

---

## 4. Staff-Level Deep Dives

### Deep Dive 1: End-to-End Idempotency Pattern
When a user clicks "Pay", mobile networks can drop right after the credit card is charged, prompting the user to hit "Pay" again.
1. **Idempotency Key Generation**: The client generates a unique UUID (e.g. \`Idempotency-Key: c9b8a...\`) prior to submitting the payment.
2. **Atomically Claim Key**: The server queries the database within a transaction:
   \`\`\`sql
   INSERT INTO payment_idempotency_keys (key, user_id, status)
   VALUES ('c9b8a...', 1234, 'PROCESSING')
   ON CONFLICT (key) DO NOTHING;
   \`\`\`
3. If the insert succeeds, this is a fresh request; proceed.
4. If conflict occurs:
   * If status is \`PROCESSING\`: Return HTTP 409 Conflict ("Transaction in progress, please wait").
   * If status is \`COMPLETED\`: Return the previously cached response payload immediately without charging the card again.

### Deep Dive 2: The Two-Phase PSP Execution (Auth & Capture)
Never debit an internal account before the card network approves, but never approve without recording the intent.
1. **Authorization**: Holds the funds on the customer's card (e.g. 7-day reserve).
2. **Capture**: Transfers the authorized funds into the merchant's merchant account after the order is fulfilled.

### Deep Dive 3: The Reconciliation Engine
* External banks deliver end-of-day settlement files (BAI2, MT940, CSV).
* An automated batch pipeline joins internal ledger entries with bank settlement rows.
* Discrepancies are categorized:
  * **Timing Differences**: Transactions settled on different calendar days.
  * **Missing Fees**: Unexpected interchange fee deductions.
  * **Unreconciled Losses**: Charges present in bank records but missing from the internal database (triggered by failed webhooks). Escalated to operations.
`
  },

  robinhood: {
    title: "Design a Real-Time Stock Brokerage (Robinhood / Trading System)",
    slug: "robinhood",
    description: "Design a high-throughput, low-latency stock trading platform with real-time market data streaming, order book matching engine, and regulatory audit ledgers.",
    difficulty: "HARD",
    category: "System Architectures",
    estimatedTimeMinutes: 45,
    tags: ["System Architectures", "Fintech", "Order Book", "Low Latency", "WebSockets", "LMAX Disruptor"],
    isPremium: true,
    contentMarkdown: `# Design a Real-Time Stock Brokerage (Robinhood Scale)

Retail stock brokerages handle two vastly different workloads: an ultra-low latency, CPU-cache-friendly order matching engine, and a massive real-time market data dissemination fanout to millions of active mobile screens.

---

## 1. System Requirements

### Functional Requirements
1. **Place Orders**: Users can place Market, Limit, and Stop-Loss orders for equity tickers.
2. **Order Execution & Matching**: Match buy and sell orders based on Price-Time Priority (FIFO).
3. **Real-time Market Data**: Stream live Level 1 (BBO: Best Bid / Offer) and Level 2 (order book depth) quotes to millions of mobile apps.
4. **Portfolio & Balances**: Instantly update user portfolio values and buying power as positions shift.
5. **Trade Confirmation & Regulatory Audit**: Immutable, timestamped records for FINRA / SEC compliance.

### Non-Functional Requirements
1. **Order Execution Latency**: Internal routing and matching engine latency $< 5\\text{ms}$.
2. **Market Data Fanout Latency**: Under 200ms from stock exchange tick to retail client glass.
3. **Zero Data Loss**: Orders and fills must be durably journaled before acknowledgment.
4. **Concurrency & Race Condition Prevention**: Prevent negative cash balance under high-frequency trading.

---

## 2. Order Book Matching Engine Architecture

\`\`\`
          LIMIT BUY ORDERS (BIDS)              LIMIT SELL ORDERS (ASKS)
      [Price: $150.00] -> [100 sh, 50 sh]   [Price: $150.05] -> [200 sh]
      [Price: $149.95] -> [300 sh]          [Price: $150.10] -> [500 sh, 100 sh]
      [Price: $149.90] -> [1000 sh]         [Price: $150.25] -> [450 sh]
                      ^                                    ^
                      |                                    |
             HIGHEST BID: $150.00                 LOWEST ASK: $150.05
                      \                                    /
                       \====== SPREAD: $0.05 =============/
\`\`\`

* **Data Structure**: A double-ended B-Tree or SkipList indexed by price. Each price level points to a doubly linked list of individual orders maintaining FIFO arrival order.
* **Concurrency Model (LMAX Disruptor Pattern)**: Rather than using mutex locks across threads, the matching engine runs single-threaded pinned to a dedicated CPU core. It reads orders sequentially from a lock-free circular ring buffer, processing over 1,000,000 orders/sec without lock contention.

---

## 3. High-Level Architecture Blueprint

\`\`\`
                           +-----------------------+
                           |  Retail Mobile Apps   |
                           +-----------+-----------+
                                       |
                                       | TLS / WebSockets
                                       v
                           +-----------------------+
                           |   API Gateway & Edge  |
                           +-----+-----------+-----+
                                 |           |
        +------------------------+           +------------------------+
        | Place Order                        | Market Data Stream
        v                                    v
+------------------------+           +------------------------+
| Order Gateway Service  |           | Market Data Fanout Svc |
| (Balance Verification) |           | (Redis PubSub / WSS)   |
+-----------+------------+           +-----------+------------+
            |                                    ^
            v In-Memory Journal                  | Live Ticks
+------------------------+           +-----------+------------+
| Matching Engine Cluster|           | Exchange Feed Handler  |
|  (C++ / Rust Engine)   |           | (Nasdaq / NYSE Feed)   |
+-----------+------------+           +------------------------+
            |
            v Fills & Executions
+------------------------+
| Clearing & Ledger Svc  |
| (PostgreSQL Database)  |
+------------------------+
\`\`\`

---

## 4. Staff-Level Deep Dives

### Deep Dive 1: Balance Pre-allocation & Atomic Buying Power Check
A user with $1,000 buying power should not be able to execute three parallel $1,000 market buys on volatile meme stocks.
1. When an order arrives at the \`Order Gateway\`, a Redis Lua script conditionally checks and holds buying power:
   \`\`\`lua
   local balance = tonumber(redis.call('get', KEYS[1]))
   local cost = tonumber(ARGV[1])
   if balance >= cost then
       redis.call('decrby', KEYS[1], cost)
       return 1
   else
       return 0
   end
   \`\`\`
2. If approved, the order advances to the matching engine.
3. If the limit order cancels or fills at a better price, the surplus held balance is atomically refunded.

### Deep Dive 2: Real-time Market Data Fanout at Scale
* Millions of users watching the AAPL ticker creates a massive fanout explosion.
* **Conflation & Throttling**: The human eye cannot process 1,000 quote changes per second. The edge market data gateways conflate ticks: if 20 price updates arrive in 100ms, only the latest quote is pushed across the client WebSocket, saving 90% bandwidth.
`
  },

  instagram: {
    title: "Design Instagram (Photo Sharing & Activity Feed)",
    slug: "instagram",
    description: "Architect a large-scale photo and video sharing platform supporting media uploads, hybrid fanout newsfeeds, and high-throughput social graphs.",
    difficulty: "MEDIUM",
    category: "System Architectures",
    estimatedTimeMinutes: 40,
    tags: ["System Architectures", "Social Media", "Feed", "Caching", "Object Storage", "CDN"],
    isPremium: true,
    contentMarkdown: `# Design Instagram (Photo Sharing & Activity Feed)

Instagram handles billions of uploaded photos, real-time activity notifications, and personalized timeline generation for over 1 billion monthly active users.

---

## 1. System Requirements

### Functional Requirements
1. **Post Photos & Videos**: Users can upload high-resolution photos and video clips with captions and tags.
2. **Follow Social Graph**: Users can follow/unfollow other accounts.
3. **News Feed Generation**: Users can view an infinite scroll timeline of recent posts from accounts they follow.
4. **Like & Comment**: Real-time interactions on posts with instantaneous count updates.
5. **Explore & Search**: Discover trending posts based on user engagement signals.

### Non-Functional Requirements
1. **Low Feed Latency**: Newsfeed page loads in $< 200\\text{ms}$.
2. **High Availability**: 99.99% availability; read traffic vastly outnumbers writes (100:1 ratio).
3. **Media Durability**: Zero data loss for uploaded images and videos.
4. **Eventual Consistency**: A new post does not need to show up on all followers' screens simultaneously, but should appear within seconds.

---

## 2. Capacity & Scale Estimation

* **Daily Active Users (DAU)**: $500\\text{ Million}$
* **New Posts Uploaded per Day**: $100\\text{ Million}$
* **Average Photo Size**: 2 MB (compressed to multiple WebP resolutions).
* **Daily Media Storage**: $100\\text{M} \\times 2\\text{ MB} = 200\\text{ TB/day} \\rightarrow 73\\text{ PB/year}$.
* **Average Read QPS**: $500\\text{M} \\times 20\\text{ feed views / 86400} \\approx 115,000\\text{ QPS}$.

---

## 3. High-Level Architecture Blueprint

\`\`\`
                                  +-----------------------+
                                  |    Mobile Client      |
                                  +-----------+-----------+
                                              |
                                              v
                                  +-----------------------+
                                  |  Cloudflare Edge CDN  |
                                  +-----------+-----------+
                                              |
                                              v
                                  +-----------------------+
                                  |      API Gateway      |
                                  +-----+-----------+-----+
                                        |           |
             +--------------------------+           +--------------------------+
             |                                                                 |
             v                                                                 v
+------------------------+                                         +------------------------+
|   Media Upload Svc     |                                         |   Feed Generation Svc  |
| (Presigned URLs to S3) |                                         | (Hybrid Fanout Engine) |
+-----------+------------+                                         +-----------+------------+
            |                                                                  |
            v                                                                  v
+------------------------+                                         +------------------------+
| Transcoding Pipeline   |                                         |  Redis Timeline Cache  |
| (FFmpeg Worker Cluster)|                                         | (ZSET of Post IDs)     |
+------------------------+                                         +------------------------+
\`\`\`

---

## 4. Feed Generation: Push vs. Pull vs. Hybrid Fanout

### Push Model (Fanout-on-Write)
* When User A posts, the system looks up all followers and inserts the \`post_id\` into every follower's Redis timeline.
* **Pros**: Feed read is instantaneous ($O(1)$ lookup in Redis).
* **Cons (The Celebrity Problem)**: If Cristiano Ronaldo (600M followers) posts, writing 600,000,000 rows melts the message queue.

### Pull Model (Fanout-on-Read)
* When a user opens the app, the system queries their follow list, fetches recent posts from all followed creators, and merges them in memory.
* **Pros**: No write amplification.
* **Cons**: Feed generation is slow and expensive at read time.

### The Hybrid Solution (Production Standard)
* **Regular Users ($< 25,000$ followers)**: Use Fanout-on-Write. Posts are pushed into followers' Redis caches immediately.
* **Celebrities / High-Follower Accounts**: Use Fanout-on-Read. Their posts are not fanned out. When a follower loads their feed, the system queries the celebrity's recent posts and merges them into the timeline dynamically.
`
  },

  yelp: {
    title: "Design Yelp (Proximity Location Search)",
    slug: "yelp",
    description: "Design a geospatial proximity search engine capable of locating nearby restaurants and businesses using Geohashes, QuadTrees, and Google S2 cells.",
    difficulty: "MEDIUM",
    category: "System Architectures",
    estimatedTimeMinutes: 40,
    tags: ["System Architectures", "Geospatial", "Proximity Search", "Geohash", "QuadTree", "Databases & Storage"],
    isPremium: true,
    contentMarkdown: `# Design Yelp (Proximity Location Search)

Proximity search systems allow users to query: *"Find the top-rated coffee shops within a 2-mile radius of my current GPS coordinates."*

---

## 1. System Requirements

### Functional Requirements
1. **Proximity Search**: Find businesses within a specified radius $R$ of latitude/longitude coordinates.
2. **Business Profiles**: View business details, operating hours, photos, and aggregate ratings.
3. **Reviews & Ratings**: Add reviews and ratings (1–5 stars) with photos.
4. **Business Registration & Updates**: Business owners can register and update their locations.

### Non-Functional Requirements
1. **Ultra-Fast Search Latency**: Geospatial queries should return within $< 100\\text{ms}$.
2. **High Read Throughput**: Search traffic is massive (100,000+ QPS), whereas business location changes are rare.
3. **Accuracy & Boundary Correctness**: Avoid missing nearby venues situated on grid boundary seams.

---

## 2. Geospatial Indexing Strategies

### Strategy 1: Geohashing
* Hierarchically subdivides the earth into a grid of characters using base-32 encoding.
* Longer prefixes represent smaller bounding boxes:
  * Length 5: $\\approx 4.9\\text{ km} \\times 4.9\\text{ km}$
  * Length 6: $\\approx 1.2\\text{ km} \\times 0.6\\text{ km}$
* **Querying**: Compute the geohash of the user's location, find its 8 neighboring bounding boxes (to handle edge boundaries), and run a fast SQL \`IN\` or Redis spatial query.

### Strategy 2: Google S2 Geometry
* Projects the sphere of the earth onto a cube, decomposing faces with Hilbert space-filling curves.
* Maps 2D spatial coordinates into a single 64-bit integer, making range queries lightning-fast using B-Tree indexing.

---

## 3. High-Level Architecture Blueprint

\`\`\`
                           +-----------------------+
                           |      User Client      |
                           +-----------+-----------+
                                       |
                                       | GET /search?lat=37.77&lng=-122.41&r=2km
                                       v
                           +-----------------------+
                           |      API Gateway      |
                           +-----------+-----------+
                                       |
                                       v
                           +-----------------------+
                           |  Search & Query Svc   |
                           +-----+-----------+-----+
                                 |           |
        +------------------------+           +------------------------+
        | Spatial Index Lookup               | Hydrate Place Details
        v                                    v
+------------------------+           +------------------------+
|  Geospatial Cache      |           | PostgreSQL / DynamoDB  |
|  (Redis GEO / S2 cells)|           | (Business Profiles DB) |
+------------------------+           +------------------------+
\`\`\`
`
  },

  strava: {
    title: "Design Strava (Fitness Tracking & Segment Leaderboards)",
    slug: "strava",
    description: "Architect a fitness tracking platform processing high-frequency GPS activity streams, map matching, spatial segment detections, and real-time leaderboards.",
    difficulty: "HARD",
    category: "System Architectures",
    estimatedTimeMinutes: 45,
    tags: ["System Architectures", "Geospatial", "Leaderboards", "Time Series", "Redis Sorted Sets"],
    isPremium: true,
    contentMarkdown: `# Design Strava (Fitness Tracking & Segment Leaderboards)

Strava processes millions of high-frequency GPS activity streams uploaded by athletes, automatically detecting when a user traversed a designated "Segment" (e.g. a steep hill climb) and updating competitive global leaderboards.

---

## 1. System Requirements

### Functional Requirements
1. **Activity Recording & Upload**: Ingest GPX / FIT files containing timestamped latitude, longitude, elevation, and heart rate telemetry.
2. **Segment Matching**: Automatically detect if any portion of an activity polyline matches a crowdsourced segment.
3. **Real-time Leaderboards**: Rank the fastest all-time efforts (KOM/QOM) on any segment with instant updates.
4. **Activity Feed & Kudos**: Social feed showing friends' recent workouts.

### Non-Functional Requirements
1. **High Ingestion Throughput**: Process bursty uploads on Sunday mornings without backlog.
2. **Accurate Map Matching**: Resilient against noisy GPS drift and signal drops under tree cover.
3. **Sub-Second Leaderboard Reads**: Leaderboard queries must return in $< 50\\text{ms}$.

---

## 2. Segment Detection Algorithm: Spatial Bounding & Polyline Frechet Distance
1. **Bounding Box Filter**: Every segment has an entry bounding box and exit bounding box indexed by Geohash. If an activity doesn't intersect both, it's discarded immediately.
2. **Frechet / Hausdorff Distance**: Measures similarity between the candidate GPS trajectory and the canonical segment path.
3. **Time Calculation**: Interpolate exact timestamps at the start and finish lines to record elapsed time down to the hundredth of a second.
`
  },

  "distributed-cache": {
    title: "Design a Distributed Cache (Redis / Memcached Cluster)",
    slug: "distributed-cache",
    description: "Design an in-memory distributed key-value caching system featuring consistent hashing, eviction policies (LRU/LFU), replication, and stampede prevention.",
    difficulty: "HARD",
    category: "Databases & Storage",
    estimatedTimeMinutes: 45,
    tags: ["Databases & Storage", "Caching", "Consistent Hashing", "Distributed Systems", "In-Memory"],
    isPremium: true,
    contentMarkdown: `# Design a Distributed Cache (Redis / Memcached Cluster)

Distributed in-memory caches sit in front of primary databases to slash read latencies from milliseconds to microseconds and absorb massive traffic spikes.

---

## 1. Core Design Goals
1. **Microsecond Latency**: Read and write operations complete in $< 1\\text{ms}$.
2. **Horizontal Scalability**: Add or remove cache nodes dynamically with minimal key movement via Consistent Hashing.
3. **High Availability**: Master-replica node pairs with automated failover via Raft or Gossip consensus.
4. **Smart Eviction**: Bound memory usage using Least Recently Used (LRU) or Least Frequently Used (LFU) algorithms.

---

## 2. Key Architecture Elements

### Consistent Hashing Ring
* Keys and cache nodes are mapped onto a 32-bit or 64-bit integer hash ring.
* Keys are assigned to the first node encountered clockwise.
* **Virtual Nodes**: Each physical server is assigned 100–250 virtual points on the ring to prevent unbalanced "hot spots" and guarantee uniform key distribution.

### Mitigating Cache Stampede (Thundering Herd)
When a hot key expires, thousands of concurrent requests miss the cache simultaneously, threatening to take down the underlying database.
* **Probabilistic Early Expiration (XFetch)**:
  $$\\Delta - \\beta \\times \\ln(\\text{rand}()) > \\text{TTL}$$
  Clients randomly refresh the cache in the background slightly before official expiration.
* **Mutex Locking**: Only the first worker to miss the cache acquires a distributed lock to recompute the database value; all other threads sleep briefly and read the refreshed cache.
`
  }
};
